### ISSUE TITLE
User registration and user login page 

### ISSUE THREAD

**Issue by eileenoo** [tum-ei-esi/wot-marketplace#11]
Add Login / Logout button.

**Comment by egekorkan** [comment]
Proposed flow 1: 
* From any page, a user can click on log in 
  * User is met with a login page consisting of a username and password field, a "forgot password" link. Below everything, there is a registration button
  * After a successful login, the user is sent to the previous or main page
* From the login page, a user can click on the registration button
  * User is met with a registration page that consists of username, email and password fields. Below everything, there is a "Confirm Registration" button
  * After clicking on Confirm Registration, the data checked and registered and logged in
* (?) If the user is logged in, the login button becomes logout.

Proposed flow 2:
* Clicking on account button from any page sends the user to a page that is:
  * A login page consisting of a username and password field, a "forgot password" link. Below everything, there is a registration button
  * User page that lists the users projects and a logout button

**Comment by egekorkan** [comment]
DONE!
