### ISSUE TITLE
Adding a new project on wotify gives error

### ISSUE THREAD

**Issue by yagizyalcintas** [tum-ei-esi/wot-marketplace#31]
**Describe the bug**
After logging into my account and clicking on New Project and filling the required places the Create Project button gives the "There is an unknown problem. Please try again later." error. If you click to it once more it gives the "Please provide your Thing Description in valid JSON format." although TD is valid.

**To Reproduce**
1. Go to 'https://wotify.org/#/login'
2. After logging in Click on 'New Project'
3. After filling the blanks Scroll down to 'Create Project' and click on it
4. See error: 'There is an unknown problem. Please try again later.'
5. Click on it again and see error: 'Please provide your Thing Description in valid JSON format.'

**Expected behavior**
A new project added to wotify.org

**Screenshots**
![WhatsApp Image 2019-07-08 at 16 51 37](https://user-images.githubusercontent.com/47401171/60820064-fb08ad80-a1a0-11e9-891c-6b90afe1627e.jpeg)
![WhatsApp Image 2019-07-08 at 16 51 58](https://user-images.githubusercontent.com/47401171/60820089-08259c80-a1a1-11e9-8da5-f5b83811adf7.jpeg)
![WhatsApp Image 2019-07-08 at 16 52 14](https://user-images.githubusercontent.com/47401171/60820106-107dd780-a1a1-11e9-9a64-b06aa3272375.jpeg)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 18.10]
 - Browser [Firefox]
 - Version [18.10]

**Comment by hasbel** [comment]
Thanks for reporting :)
here we have to different bugs:

- Design: the long description is set to a max of 500 chars. This is too small and should be much bigger.
- Front-end: when the server responds with an error and the user changes the project and tries again, the front-end refuses to resend and says the JSON in the TD is not correct ...

**Comment by egekorkan** [comment]
Solved in #32
