### ISSUE TITLE
Adapt Markdown View in Project 'General' Section

### ISSUE THREAD

**Issue by eileenoo** [tum-ei-esi/wot-marketplace#6]
Even when pasting the hard coded markdown, the view is not really correct. For example the bullet points are to far left, spaces are not detected etc. 

![screenshpt_project_general_short](https://user-images.githubusercontent.com/8364973/56090744-8d512c00-5ea6-11e9-972c-0a0d50bf1d52.png)

**Comment by egekorkan** [comment]
Could you try with different flavors? 
https://vue-showdown.js.org/guide/#flavor
currently it uses github, maybe others work better

**Comment by eileenoo** [comment]
I adapted it for the screenshot but for the final prototype we need to change this :)

**Comment by egekorkan** [comment]
fixed now
